# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 829)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.textLabel1.setGeometry(QtCore.QRect(150, 500, 61, 16))
        self.textLabel1.setObjectName("textLabel1")
        self.HistoricalOprations_ListView = QtWidgets.QListView(self.centralwidget)
        self.HistoricalOprations_ListView.setGeometry(QtCore.QRect(820, 20, 241, 421))
        self.HistoricalOprations_ListView.setObjectName("HistoricalOprations_ListView")
        self.labelCapture = QtWidgets.QGraphicsView(self.centralwidget)
        self.labelCapture.setGeometry(QtCore.QRect(50, 220, 271, 261))
        self.labelCapture.setObjectName("labelCapture")
        self.processing_Image = QtWidgets.QGraphicsView(self.centralwidget)
        self.processing_Image.setGeometry(QtCore.QRect(460, 220, 271, 261))
        self.processing_Image.setObjectName("processing_Image")
        self.textLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.textLabel2.setGeometry(QtCore.QRect(550, 500, 91, 16))
        self.textLabel2.setObjectName("textLabel2")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(460, 180, 211, 31))
        self.horizontalSlider.setMaximum(50)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(680, 180, 51, 31))
        self.doubleSpinBox.setMaximum(50.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(900, 450, 93, 28))
        self.clearButton.setObjectName("clearButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.noise = QtWidgets.QMenu(self.menuTool)
        self.noise.setObjectName("noise")
        self.Color = QtWidgets.QMenu(self.menuTool)
        self.Color.setObjectName("Color")
        self.menuEnhancement = QtWidgets.QMenu(self.menuTool)
        self.menuEnhancement.setObjectName("menuEnhancement")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionGauss_noise = QtWidgets.QAction(MainWindow)
        self.actionGauss_noise.setObjectName("actionGauss_noise")
        self.actionPepper_noise = QtWidgets.QAction(MainWindow)
        self.actionPepper_noise.setObjectName("actionPepper_noise")
        self.actionbox_filter = QtWidgets.QAction(MainWindow)
        self.actionbox_filter.setObjectName("actionbox_filter")

        self.actionRecover = QtWidgets.QAction(MainWindow)
        self.actionRecover.setObjectName("actionRecover")
        self.action2Gray = QtWidgets.QAction(MainWindow)
        self.action2Gray.setObjectName("action2Gray")
        self.actionBlur = QtWidgets.QAction(MainWindow)
        self.actionBlur.setObjectName("actionBlur")
        self.actionHist = QtWidgets.QAction(MainWindow)
        self.actionHist.setObjectName("actionHist")
        self.actionLog = QtWidgets.QAction(MainWindow)
        self.actionLog.setObjectName("actionLog")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.noise.addAction(self.actionGauss_noise)
        self.noise.addAction(self.actionPepper_noise)
        self.Color.addAction(self.action2Gray)
        self.menuEnhancement.addAction(self.actionHist)
        self.menuEnhancement.addAction(self.actionLog)
        self.menuTool.addAction(self.actionRecover)
        self.menuTool.addAction(self.noise.menuAction())
        self.menuTool.addAction(self.menuEnhancement.menuAction())
        self.menuTool.addAction(self.Color.menuAction())
        self.menuTool.addAction(self.actionBlur)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "王颜婷2020060903026"))
        self.textLabel1.setText(_translate("MainWindow", "原图像"))
        self.textLabel2.setText(_translate("MainWindow", "处理后图像"))
        self.clearButton.setText(_translate("MainWindow", "清除"))
        self.menuFile.setTitle(_translate("MainWindow", "文件(F)"))
        self.menuTool.setTitle(_translate("MainWindow", "工具(T)"))
        self.noise.setTitle(_translate("MainWindow", "噪声"))
        self.Color.setTitle(_translate("MainWindow", "颜色处理"))
        self.menuEnhancement.setTitle(_translate("MainWindow", "增强"))
        self.actionOpen.setText(_translate("MainWindow", "打开(O)"))
        self.actionSave.setText(_translate("MainWindow", "保存(S)"))
        self.actionGauss_noise.setText(_translate("MainWindow", "高斯噪声"))
        self.actionPepper_noise.setText(_translate("MainWindow", "椒盐噪声"))

        self.actionRecover.setText(_translate("MainWindow", "恢复"))
        self.action2Gray.setText(_translate("MainWindow", "灰度化"))
        self.actionBlur.setText(_translate("MainWindow", "模糊"))
        self.actionHist.setText(_translate("MainWindow", "直方图增强"))
        self.actionLog.setText(_translate("MainWindow", "对数增强"))

